### ISSUE TITLE
packetfile interface fails to pipe data to windows wireshark 4.4.0

### ISSUE THREAD

**Issue by mnassy** [siemens/edgeshark#67] opened 2024-09-19 22:58 UTC
**PROBLEM:**

Receive the following error message when launching Wireshark 4.4.0 from the web link http://lfqdn:5001/w: 

Error from extcap pipe: time="2024-09-19T15:43:37-07:00" level=error msg="--container information missing or invalid"
time="2024-09-19T15:43:37-07:00" level=error msg="finished with status code 1"

**TROUBLESHOOTING:**

If i manually move cshargextcap-amd64.exe and containershark.ico from extcap to extcap\wireshark and make a link to both files that resides in extcap i can get the docker host capture interface to work.

**WORK AROUND**

It works when using Wireshark 4.2.7.

**Comment by thediveo** [comment] 2024-09-20 06:00
duplicate of https://github.com/siemens/cshargextcap/issues/20

**Closed by thediveo** 2024-09-20 06:00 UTC
